server:
  port: 8048

spring:
  application:
    name: seven-jalas
  datasource:
    url: jdbc:postgresql://postgres
    username: spring
    password: 1234
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: schema_version
  mail:
    host: smtp.gmail.com
    port: 587
    username: jalas.seven@gmail.com
    password: jalas7jalas
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jalas:
  base-url: localhost:3000